### ISSUE TITLE
Wrong twitter account on footer

### ISSUE THREAD

**Issue by Balastrong** [Schrodinger-Hat/osday-2023#117]
The Twitter account in the footer ([OSDayDev](https://twitter.com/OSDayDev)) seems to be invalid

https://github.com/Schrodinger-Hat/osday-2023/blob/88715b73a229c63f0b92866b14be0606501430b5/components/Footer.tsx#L16-L18

**Comment by davideimola** [comment]
Thanks the URL must be https://twitter.com/schrodinger_hat! You are free to give it a try @Balastrong!
