### ISSUE TITLE
Add Agenda component to website

### ISSUE THREAD

**Issue by 404answernotfound** [Schrodinger-Hat/osday-2023#156]
Before we have an actual agenda it would be useful to create an Agenda component that will showcase speakers and timetables once we go live with the names of the Speakers

**Comment by TheJoin95** [comment]
I got this broski

**Comment by nicpuppa** [comment]
Let’s goooo

**Comment by TheJoin95** [comment]
Added the mockup, you can use it to develop the timeline bro
