### ISSUE TITLE
Add speakers Hero component on homepage to showcase speakers

### ISSUE THREAD

**Issue by 404answernotfound** [Schrodinger-Hat/osday-2023#157]
We could add an additional Hero component to showcase Speakers one at a time on each refresh between primary Hero and Sponsors

**Comment by TheJoin95** [comment]
We should have a dedicated page too.
Do you want to open another issue for the page?

**Comment by nicpuppa** [comment]
> We should have a dedicated page too.
> Do you want to open another issue for the page?

We already had a speakers page

**Comment by TheJoin95** [comment]
Sorry, I meant a personal speaker page for each one

**Comment by nicpuppa** [comment]
Idk, maybe we can only create a component `speaker-info` and use it inside Speakers page. The new Hero component should redirect to Speakers page with an anchor to the correct speaker

**Comment by 404answernotfound** [comment]
I'll start by creating a generic hero component for this, then we can use it wherever
