### ISSUE TITLE
Add OVH as Diamond Sponsor

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#162]
![ovh_logo](https://user-images.githubusercontent.com/72783243/214625042-64ba75ac-a1a1-4805-9cd5-7d2c11ddc886.png)

site: [ovhcloud.com](https://us.ovhcloud.com/)

**Comment by Nareshchoudhary02** [comment]
Hey, @Wabri assign me this issue I will try to solve this issue 😁.

**Comment by Wabri** [comment]
I can do that, but we are waiting the mediakit from ovh to set up the right logo they want.

**Comment by Nareshchoudhary02** [comment]
@nicpuppa on it .
