### ISSUE TITLE
Add PMD as community partner

### ISSUE THREAD

**Issue by nicpuppa** [Schrodinger-Hat/osday-2023#164]
![Logo_bianco](https://user-images.githubusercontent.com/72783243/214638946-4e8693db-708b-48ee-a860-9f3abc91e466.png)

Link: https://www.productmanagementday.com/

**Comment by Nareshchoudhary02** [comment]
Hey, @nicpuppa assign me this issue I will try to fix this good first issue 😁.

**Comment by nicpuppa** [comment]
Here you go @Nareshchoudhary02, thank you!
