### ISSUE TITLE
Center align social icons and modify footer

### ISSUE THREAD

**Issue by Nareshchoudhary02** [Schrodinger-Hat/osday-2023#171]
I propose that the social icons on the website be centered for better visual alignment. Additionally, I suggest modifying the footer to include more information such as the company's address and contact information.

<img width="1440" alt="modifiedFooter" src="https://user-images.githubusercontent.com/107427909/215302670-614cbe69-3ed4-4e73-b9bb-cb7d58bc39f9.png">

**Comment by Nareshchoudhary02** [comment]
@nicpuppa I open a issue, to discuss this modification.

**Comment by TheJoin95** [comment]
You should open a PR

**Comment by Nareshchoudhary02** [comment]
> You should open a PR
Done ! 😄

**Comment by Nareshchoudhary02** [comment]
> You should open a PR

The PR has been closed without review 😕.

**Comment by TheJoin95** [comment]
No needs of implementing this issue as discussed on discord server of the project community
