### ISSUE TITLE
Call for volunteers typo

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#175]
There is a typo on cfv page "Call for volunteers" doesnt have the o:

![Screenshot 2023-01-31 at 11 52 17](https://user-images.githubusercontent.com/12409541/215740691-598d2634-69c2-4ba8-9611-720251643186.png)

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue

**Comment by nicpuppa** [comment]
Thank you @tarunsamanta2k20, you can work on it!

**Comment by davideimola** [comment]
Closing the issue as the PR has been merged!
