### ISSUE TITLE
Pensieri in codice as community sponsor

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#188]
Logo: ...

site: https://pensieriincodice.it/

**Comment by mateonunez** [comment]
Hey, @Wabri I would like to contribute to this if it's ok for you.

**Comment by TheJoin95** [comment]
Go on :)

Il ven 17 feb 2023, 20:10 Mateo Nunez ***@***.***> ha scritto:

**Comment by mateonunez** [comment]
Just a small problem with the logo.... The letters of the name are hidden by the background of the page.

![image](https://user-images.githubusercontent.com/11861080/219768291-84e8fc9d-24d5-4f02-9430-3618e1d6edcc.png)

**Comment by TheJoin95** [comment]
We should ask for a negative version then

**Comment by nicpuppa** [comment]
Hi @mateonunez I’m still waiting valerio to send to us the svg logo with blank text 👍🏻

**Comment by mateonunez** [comment]
Awesome! Let me know when the logo is ready so I can create the PR. 😁

**Comment by valeriogalano** [comment]
Hi guys,
here an svg file containing original logo

![logo_PiC](https://user-images.githubusercontent.com/342634/219857608-e94dd71c-0a2c-4aa8-830e-0bacd0bca7a5.svg)

**Comment by valeriogalano** [comment]
Probably you also need fonts:
[beautiful_and_openhearted.zip](https://github.com/Schrodinger-Hat/osday-2023/files/10774003/beautiful_and_openhearted.zip)
[courier-10-pitch-regular_J2tvz.zip](https://github.com/Schrodinger-Hat/osday-2023/files/10774008/courier-10-pitch-regular_J2tvz.zip)

**Comment by TheJoin95** [comment]
We would like to not add any other fonts on the website. Would it be possible to have it already included in the svg file?

**Comment by valeriogalano** [comment]
@TheJoin95 is this ok? I'm not an expert in graphic design...

![logo_PiC](https://user-images.githubusercontent.com/342634/219863934-36787621-f5be-4cfb-8874-37212aa04e0d.svg)

**Comment by nicpuppa** [comment]
> @TheJoin95 is this ok? I'm not an expert in graphic design...
> 
> ![logo_PiC](https://user-images.githubusercontent.com/342634/219863934-36787621-f5be-4cfb-8874-37212aa04e0d.svg)

Is it possible to have the letters in white ?

**Comment by valeriogalano** [comment]
> > @TheJoin95 is this ok? I'm not an expert in graphic design...
> > ![logo_PiC](https://user-images.githubusercontent.com/342634/219863934-36787621-f5be-4cfb-8874-37212aa04e0d.svg)
> 
> Is it possible to have the letters in white ?

I can change title's color, but actually the PIC logo includes the whole square. Can't we add it as is?

**Comment by mateonunez** [comment]
> @TheJoin95 is this ok? I'm not an expert in graphic design...
> 
> ![logo_PiC](https://user-images.githubusercontent.com/342634/219863934-36787621-f5be-4cfb-8874-37212aa04e0d.svg)

Hi guys, is this logo okay or should we wait for the one with white lettering?

**Comment by nicpuppa** [comment]
> > @TheJoin95 is this ok? I'm not an expert in graphic design...
> > ![logo_PiC](https://user-images.githubusercontent.com/342634/219863934-36787621-f5be-4cfb-8874-37212aa04e0d.svg)
> 
> Hi guys, is this logo okay or should we wait for the one with white lettering?

Hi @mateonunez, the correct logo is the one with black character and orange square!
