### ISSUE TITLE
Add PermitIO as new Silver sponsor

### ISSUE THREAD

**Issue by nicpuppa** [Schrodinger-Hat/osday-2023#202]
![permitio](https://user-images.githubusercontent.com/72783243/222137487-321d6547-3d2c-4d7d-a8c9-034c9b10bcf8.svg)

Link: https://www.permit.io/

**Comment by pewpewnor** [comment]
Hello, i would like to help with this issue for you guys, if i can.
Is it enough to add the .svg image to /public and add a new image component in the SponsorTable.tsx ?
