### ISSUE TITLE
Add DataPizza as Media Partnership

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/osday-2023#212]
We can select one of the following logos :) 

![DATAPIZZA_LOGOTIPO – mono_R](https://user-images.githubusercontent.com/14623986/223381540-08497ea4-e326-4260-8736-b92c4a8c5afb.png)
![DATAPIZZA_LOGOTIPO_light](https://user-images.githubusercontent.com/14623986/223381573-587ed499-e002-4758-8410-edfe77f53b6d.png)
![DATAPIZZA_LOGOTIPO – mono_L](https://user-images.githubusercontent.com/14623986/223381648-47a9c805-a3c3-4fd9-b1ff-238014ae30a2.png)

**Comment by pewpewnor** [comment]
Hello, is there a link for datapizza so that when the image is clicked, it would go to the link?

**Comment by nicpuppa** [comment]
Hi @pewpewnor you can use this link: https://linkedin.com/company/datapizza
