### ISSUE TITLE
Prepare event on eventbrite

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#285]

**Comment by TheJoin95** [comment]
Creata draft su eventbrite: necessario preparare una descrizione, modificare la timeline e decidere un giorno per l'apertura dei biglietti, as well as il giorno della conf

**Comment by Wabri** [comment]
Evento: https://www.eventbrite.it/myevent?eid=731947624047
Preview: https://www.eventbrite.it/e/731947624047/preview/
