### ISSUE TITLE
Prepare cfp on sessionize

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#288]

**Comment by davideimola** [comment]
Created a first draft into Sessionize.
Now we must work together to populate as required.

We must decide also when to request the full license for the CfP.

**Comment by 404answernotfound** [comment]
@davideimola where do we sit on this one?

**Comment by davideimola** [comment]
@404answernotfound the CfP is almost ready, as @Wabri said in Discord it is better if we take a look at it all together.

Also, we may work on providing a banner for the CfP. @TheJoin95 do you have any idea on the design?

I have already done the license part, and they have approved our event.

**Comment by TheJoin95** [comment]
If we would like to have the same design we should made it with Canva using nana bianca's template

The dates are 14-15 March 2024

**Comment by Wabri** [comment]
The dates are 7-8 march 2024

**Comment by Wabri** [comment]
Manage session: https://sessionize.com/app/organizer/event/12982
Public (not open yet): https://sessionize.com/opensourceday24/?e=0c5dad
