### ISSUE TITLE
Sharing dynamic virtual ticket from the website with the name as it was for the vercel conference

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#313]
From eventbrite we are going to redirect to osday e.g. https://2024.osday.dev/ticket?eid=717125340197&oid=8088718889

where eid is the eventId and oid is the orderId from eventbrite. We can then do a request to their API, get the data and show the ticket dynamically.

We can decide to handle this in a NextJS API so we can hide the parameters, create an UUID and redirect to a /ticket/[uuid] page specific per the user.

**Comment by TheJoin95** [comment]
Design approved

![Image](https://github.com/Schrodinger-Hat/osday/assets/6616203/ca849319-46e8-45ce-959f-98597c36394c)

**Comment by 404answernotfound** [comment]
Great work Miki!

**Comment by TheJoin95** [comment]
![Image](https://github.com/Schrodinger-Hat/osday/assets/6616203/6bb1572c-bc41-4406-abed-8b687ad3db29)
