### ISSUE TITLE
CTA for tickets in sharing a ticket

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/osday-2023#319]
When sharing the ticket to social and opening it in a browser it would be better if also we can put a call to action to redeem a new ticket!

**Comment by TheJoin95** [comment]
Any news on this one?

**Comment by TheJoin95** [comment]
There are not so much ticket shared, I proposed to redirect the user directly to X or LinkedIn sharer. Any thoughts @Wabri @nicpuppa @lorepieri ?

**Comment by davideimola** [comment]
> Any news on this one?

I haven't had the time to work on it yet!
