### ISSUE TITLE
github url error in terminal version

### ISSUE THREAD

**Issue by ziriuz84** [Schrodinger-Hat/osday-2023#336]
In the Terminal version of the website if I run the command Github it opens a popup to https://github.com/https://github.com/schrodinger-hat/ which is wrong.

**Comment by TheJoin95** [comment]
Thank you for reporting this issue! I'll have a look if there is no one willing to take this :)

**Comment by TheJoin95** [comment]
Deploying the latest changes as the issue is now solved!

**Comment by ziriuz84** [comment]
Wow, blazingly fast! :open_mouth:
