### ISSUE TITLE
Social Posts until OSDay 2024

### ISSUE THREAD

**Issue by Readpato** [Schrodinger-Hat/osday-2023#340]
Target: Do minimum 3 posts a week

**December '23**
Week: 04-10
- [x] Verona - LinkedIn Event@ 05/12/23
- [x] Call for sponsor @ 06/12/23

Week: 11-17
- [x] GitHub Wrapped@ 12/12/2023
- [x] Talk 2022 - Liran Tal@ 13/12/2023
- [x] Tickets @ 14/12/2023
- [x] Random post @ 15/12/2023 (already scheduled)

Week: 18-24

- [x] Random Post @ 18/12/2023 (already scheduled)
- [x] Call for Speaker@ 19/12/2023
- [x] Talk 2022 - TBD @ 20/12/2023
- [x] Video Short Montini @ 21/12/2023
- [x] Christmas @ 22/12/2023

Week: 25-31
- [x]  @ 26/12/2023
- [x]  @ 27/12/2023
- [x]  @ 28/12/2023

**January '24**
Week: 01-07
- [x]  New Years Eve @ 01/01/2024
- [x]  @ 02/01/2024
- [x]  @ 03/01/2024
- [x]  @ 04/01/2024

Week: 08-14
- [x]  @ 09/01/2024
- [x]  @ 10/01/2024
- [x]  @ 11/01/2024

Week: 15-21
- [x]  @ 16/01/2024
- [x]  @ 17/01/2024
- [x]  @ 18/01/2024

Week: 22-28
- [x]  @ 23/01/2024
- [x]  @ 24/01/2024
- [x]  @ 25/01/2024

Week: 29-31
- [x]  @ 30/02/2024
- [x]  @ 31/02/2024

**Februray '24**
Week 01  - 04
- [x]  @ 01/02/2024

Week: 05-11
- [x]  @ 06/02/2024
- [x]  @ 07/02/2024
- [x]  @ 08/02/2024

Week: 12-18
- [x]  @ 13/02/2024
- [x]  @ 14/02/2024
- [x]  @ 15/02/2024

Week: 19-25
- [x]  @ 20/02/2024
- [x]  @ 21/02/2024
- [x]  @ 22/02/2024

Week: 26-29
- [x]  @ 27/02/2024
- [x]  @ 28/02/2024
- [x]  @ 29/02/2024

**March '24**
Week: 01 - 08
- [x]  @ 01/03/2024
- [x]  @ 02/03/2024
- [x]  @ 03/03/2024
- [x]  @ 04/03/2024
- [x]  @ 05/03/2024
- [x]  @ 06/03/2024
- [x]  @ 07/03/2024
- [x]  @ 08/03/2024

**Comment by nicpuppa** [comment]
Related to #269

**Comment by TheJoin95** [comment]
Done. We can evaluate if opens a similar ticket for the follow-up of the oaday24
