### ISSUE TITLE
Add Birdie as Silver Sponsorship

### ISSUE THREAD

**Issue by 404answernotfound** [Schrodinger-Hat/osday-2023#344]
<img width="1910" alt="Birdie – logo – white + Green RGB" src="https://github.com/Schrodinger-Hat/osday/assets/79904453/a934c921-1303-4efb-a7f0-9361f007ed2f">

**Comment by nicpuppa** [comment]
@404answernotfound we need the SVG

**Comment by 404answernotfound** [comment]
![Birdie – logo – white + Green RGB](https://github.com/Schrodinger-Hat/osday/assets/79904453/25a67018-d33c-47d8-8cb6-1eff0e9b4745)
