### ISSUE TITLE
Birdie thank you post

### ISSUE THREAD

**Issue by 404answernotfound** [Schrodinger-Hat/osday-2023#346]
Text to be used:

Birdie equips home care providers with essential digital tools for managing, delivering and championing outstanding care. Birdie provides mobile and desktop software used by care businesses of all sizes to manage care delivery, rostering, finance and auditing. Alongside their technology, the Birdie team provide a host of free, practical resources and support for the care industry including courses, workshops and community meet-ups.

Birdie works by the side of partners to uplift them today, and help them fly in the future.

Birdie is always looking to grow its flock, if you're interested - take a look at our open opportunities [here](https://www.birdie.care/join-us#open-roles) :blue_heart:

**Comment by nicpuppa** [comment]
Post scheduled
