### ISSUE TITLE
Update Pensieri in codice logo

### ISSUE THREAD

**Issue by valeriogalano** [Schrodinger-Hat/osday-2023#350]
Please, can you update partner logo for Pensieri in codice?

New logo SVG can be found here: https://github.com/valeriogalano/pensieriincodice-assets/blob/main/images/pensieriincodice-2-logo.svg

Thanks you!

**Comment by TheJoin95** [comment]
Would it be possible for you to open a pr?

**Comment by valeriogalano** [comment]
Done.

Thanks you.

**Comment by TheJoin95** [comment]
Merged

**Comment by nicpuppa** [comment]
Hey @valeriogalano you only replaced the logo, but you didn't add `pensieri in codice` among the community partner. Let me know if you have time to make a PR 💪 

cc @TheJoin95

**Comment by valeriogalano** [comment]
Hi @nicpuppa, I supposed it was among partners like past year. I'm afraid I don't know where to add it.
