### ISSUE TITLE
From Monolith To Microservices – And Beyond - Peter van Vliet

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#357]
The monolithic architecture is - after being overshadowed by microservices for years - making a comeback. This may seem strange, but it's far from it. In the last few years we've learned how to build them in a way that allows for migration to services painlessly. In this talk, we'll explore new insights and developments in the field of future-proof and scalable application architecture. Join me if you want to learn how to build scalable applications with the simplicity of a monolith and the resilience of microservices.

**Comment by BJLAP** [comment]
Very interesting, this has the potential to simplify complex infrastructures and make them easier to manage!
