### ISSUE TITLE
Managing In The Open, Managing Contributions: The challenges of OSPO developers management - Ahmed Sobeh

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#366]
Managing an Open Source Program Office (OSPO) team is undoubtedly a unique experience. In this talk I will discuss the unique challenges and best practices for managing software developers in an OSPO environment. I will cover topics such as managing remote teams, maintaining the career progression of OSPO developers, fostering a culture of collaboration and collaborating with the open source community. I will also explore the role of performance metrics in managing software developers in an OSPO, how to align those metrics withe the goals of the organisation and how to help developers balance the needs of the organisation with the needs of the open source community.
The talk will be particularly relevant for managers who are new to the OSPO environment or who are looking to expand their skills in managing software developers in an open source context. 
Attendees will gain valuable insights into the unique challenges of managing software developers in an OSPO, as well as practical tips and strategies for building and managing coherent, efficient teams in this context.

**Comment by ahmedsobeh** [comment]
Thanks for the opportunity! I will be giving this talk at [State of Open Con 24](https://sched.co/1XkGW) next week
