### ISSUE TITLE
Crafting Child-Friendly Digital Worlds - Jara Puype

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#383]
In this session, I will explore the role of open source technologies in creating child-friendly digital interfaces. We'll discuss how open source tools and frameworks can be effectively utilized to design intuitive and engaging user experiences for young users. The talk will highlight the importance of community-driven development in shaping educational and interactive web environments.

**Comment by TheJoin95** [comment]
Closing as we received an email from the speaker asking to withdraw his talk as is not available anymore for event's date.
