### ISSUE TITLE
From OpenAI to Opensource AI: Navigating Between Commercial Ownership and Collaborative Openness - Raphael Semeteys

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#390]
This presentation explores the evolution of generative AI, highlighting the trajectories of various models such as GPT-4, and examining the dynamics between commercial interests and the ethics of open collaboration. We offer an in-depth analysis of the levels of openness of different language models, assessing various components and aspects, and exploring how the (de)centralization of computing power and technology could shape the future of AI research and development.
Additionally, we explore concrete examples like LLaMA and its descendants, as well as other open and collaborative projects, which illustrate the diversity and creativity in the field, while navigating the complex waters of intellectual property and licensing.

**Comment by raphiki** [comment]
I will give this talk next week in London at [State of Open Con 2024](https://sched.co/1Xl1v).

**Comment by raphiki** [comment]
Join me in exploring the transformative world of AI and Language Models at the intersection of open collaboration and proprietary control. Delve into the evolution of Generative AI and understand the balance between commercial interests and open-source ethics. My presentation offers a comprehensive analysis of AI’s openness, its impact on research, and future development. Discover examples like LLaMA, and other groundbreaking projects that navigate the complexities of intellectual property.

**Comment by raphiki** [comment]
The talk is based on a two-part article I co-authored on LLM openness:
* https://blog.worldline.tech/2023/10/25/open-gen-ai.html
* https://blog.worldline.tech/2023/12/19/open-gen-AI-part2.html

**Comment by raphiki** [comment]
Here is a short video presenting my talk (for SOOC'24): https://twitter.com/RaphaelSemeteys/status/1751596411706114557
