### ISSUE TITLE
The open source build tool everyone needs - Santosh Yadav

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#397]
Developers invest time writing code, ensuring the code is well structured, going through code reviews, and then ending up waiting for builds, tests, end-to-end tests to pass on local machines and CI.
For larger open source and enterprise projects, the challenge is building what is changed; Google has been doing this for years; let me tell you about Nx, the tool built by Ex-Googlers, which can help give superpower to your developers; it gives you:
Ability to create more structured code 
Speed up local, and CI runs
Identify flaky tests 
Ability to share build cache
More detailed report of CI usage 
Ability to distribute your tasks to multiple agents
If you are struggling with any of the above, what are you waiting for? Join me in this talk and enable the developer superpower for your team.

**Comment by santoshyadavdev** [comment]
Thank you for the opportunity :)

**Comment by palmiak** [comment]
@santoshyadavdev - can't wait to meet you there in person :)

**Comment by raro42** [comment]
Need to see this. Hope the topic makes it to the main stage.

**Comment by danywalls** [comment]
Vote up!

**Comment by umairhm** [comment]
All the best @santoshyadavdev 👍🏼
