### ISSUE TITLE
sponsor video carousel

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#461]

**Comment by TheJoin95** [comment]
@Wabri could you please list here all the sponsor that we need to add in the carousel ?

**Comment by Wabri** [comment]
- spindox
- suse
- claranet
- nephila
- sparkfabrik
- birdie
- TRANSACT

ATM

**Comment by TheJoin95** [comment]
Could you please set a reminder on this for me? @Wabri

**Comment by TheJoin95** [comment]
On it

**Comment by TheJoin95** [comment]
https://drive.google.com/file/d/14IPldqhmn8AaLSCMQVcRvFeaF5OLt4pp/view?usp=drive_link

**Comment by Wabri** [comment]
Done some tests and the background in white is not work so well

**Comment by TheJoin95** [comment]
Updated the carousel, generated two videos. Added blue screen, all good, closing
