### ISSUE TITLE
Send email to online attendees with streaming links

### ISSUE THREAD

**Issue by nicpuppa** [Schrodinger-Hat/osday-2023#473]

**Comment by TheJoin95** [comment]
I would say that we can create a redirect on our site which would redirect to the youtube stream for the dedicated track.

This because of a possible incident on youtube video ID otherwise it won't be easy for the attendees to find again the stream url

**Comment by TheJoin95** [comment]
Do we have the two links today?

**Comment by Wabri** [comment]
We have the 4 links:
- day 1
  - alpha https://youtube.com/live/_mA4mvYpU68
  - beta https://youtube.com/live/te8tNwnej0M
- day 2
  - alpha https://youtube.com/live/8owI4xBEIl0
  - beta https://youtube.com/live/Va6vIYCVxj0

**Comment by TheJoin95** [comment]
We should add these links on the website as well

**Comment by Wabri** [comment]
We can close this after #497
