### ISSUE TITLE
Add link to this project in the footer(?)

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#48]

**Comment by TheJoin95** [comment]
Can you explain this pls?

**Comment by Wabri** [comment]
Simply create a redirect to https://github.com/Schrodinger-Hat/osday-2023 somewhere in https://osday.dev/ to let people join here and solve some issues.

Maybe even on the actual footer:
![Screenshot 2022-11-17 at 13 01 15](https://user-images.githubusercontent.com/12409541/202441247-3537e65d-601b-4fa3-aff4-c1edc1797383.png)

**Comment by TheJoin95** [comment]
Closing because #52
