### ISSUE TITLE
Add mia-platform as silver sponsor

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#481]
https://mia-platform.eu/

![miaplatform](https://github.com/Schrodinger-Hat/osday/assets/12409541/a2265bcf-f6b8-41a1-ac6c-b1b0469f9d35)

**Comment by TheJoin95** [comment]
The logo should have the white text

**Comment by TheJoin95** [comment]
@Wabri sent an email to them asking if they could provide us the right logo

**Comment by Wabri** [comment]
<img width="2378" alt="Open Source Day 2024 Speaker White Lockup" src="https://github.com/Schrodinger-Hat/osday/assets/12409541/6fd9d477-766b-4c2e-96c8-3b455dc27260">
