### ISSUE TITLE
Verify if it's possible to manage 2 streams from a single director cabin

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#483]
Needs to be asked to Claudio or Nana

**Comment by nicpuppa** [comment]
It is not possible, in the other rooms you can only stream what it happens in the main stage AFAIK. If we want to stream something else, we need a second direction

**Comment by TheJoin95** [comment]
@Wabri thought that was possible because of something Claudio said to him last time, but it needs to be verified with him.

If that it's the case it would be easier for us to manage the whole thing so we can free up one person

**Comment by nicpuppa** [comment]
Not really, I think only one person can't manage both direction. Also in the room there isn't a lot of space for another laptop

**Comment by Wabri** [comment]
A second direction can be done without problem because all the video/audio exits can be isolated from a room to another, I'm pretty sure about this. The problem will be the restream the same audio/video to the other room, but I'm in contact with claudio and we are thinking on how to handle it.

**Comment by TheJoin95** [comment]
@Wabri if it's ok for you, I think we can close this one

**Comment by Wabri** [comment]
Yes, they confirm that is possible to do it and I'll do a test next week!
