### ISSUE TITLE
Remove Leo Vernisse to the list of speakers of the agenda

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#491]

**Comment by nicpuppa** [comment]
He is not taking part at the conference

**Comment by Wabri** [comment]
So remove his name from the list of the talk in the first day

**Comment by TheJoin95** [comment]
@Wabri what's the matter? From where? On the agenda website it's not there

**Comment by Wabri** [comment]
![Screenshot_20240227-135202-416.png](https://github.com/Schrodinger-Hat/osday/assets/12409541/c9ef8469-5d81-443f-b6c4-c8c748475cad)

**Comment by TheJoin95** [comment]
Oh oke, he's there as a second speaker
