### ISSUE TITLE
Add MCs page

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#494]
Something similar to the agenda? Is it possible to integrate to the agenda page?

**Comment by TheJoin95** [comment]
Yes, I'll try to do it

**Comment by TheJoin95** [comment]
@Wabri I need the final table for MCs, could you update it or write it here?

**Comment by TheJoin95** [comment]
Is the following?

  | Alpha | Beta
-- | -- | --
7 Morning | Pieri+ | Pato+
7 Afternoon | Miki+Maciek Palmowski | Dave+
8 Morning | Miki+Noah | Dave+
8 Afternoon | Pieri+ | Pato+

**Comment by Wabri** [comment]
I'm managing the 7m and 8a, can you create empty space for the second mc for now? I'll update when I manage to get the other 2 confirmation!
