### ISSUE TITLE
main page of osday

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#507]
Should we consider to update the main page with something new?

**Comment by TheJoin95** [comment]
What do you mean?

**Comment by Wabri** [comment]
ATM there are the reference on the latest edition, maybe we should change to the current event. Maybe a countdown? i dont know. Lets discuss about it!

**Comment by 404answernotfound** [comment]
It would be lovely to have something different but do we have energy/space to do that?
