### ISSUE TITLE
FAQ Page?

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#508]
Does it make sense create a FAQ page with this infos?

- How does the after party work? Can I bring a guest?
The after party is organized at 18:30 inside the Bar inside the venue of the event. The seats are limited to only the in-presence attendees. Unfortunately we have estimated an amount of people considering a possible ticket drop-off on the day of the event, so by entering the venue you will get something to show at the staff to get drinks.
In case the amount is exceeded unfortunately we can't give it anymore, but we hope you may still enjoy the network opportunity.
- Can I arrive later than afternoon?
Of course! You can enter whenever you want. A Staff member will be at the entrance just to check the tickets and give you the badge.
- Will there be some offered food?
We are offering food only during the after party as aperitif. We have organized a discounted price with the venue, both for launch or coffee breaks. You can buy your own food at the following link: https://eventi.thestellaritaly.it/events/
- Is there an online version? Are you going to upload the talks?
The event will be broadcasted on YouTube for both days and both tracks. You can see the recordings whenever you want. Also, all the talks will be uploaded separately a few days after the event.
- Do I need any documents to enter the venue?
No, only the ticket is needed.
- Is there any program for the event?
Yes, the agenda is available on the conference website! https://2024.osday.dev/agenda-compact

As we have discovered different strikes involving the conference days affecting planes and trains, we have updated the website with further information to reach the venue: https://2024.osday.dev/venue.

If you have any other questions please reach us with an email at [events@schrodinger-hat.it](mailto:events@schrodinger-hat.it) or through a direct message to our LinkedIn page.

**Comment by TheJoin95** [comment]
Yes, it makes totally sense in my opinion
