### ISSUE TITLE
Send out newsletter follow-up osday

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#516]
- upload emails into newsletter list
- add feedback form
- add splitted video playlist links
- add ecommerce link
- add gallery link
- add useful links

**Comment by TheJoin95** [comment]
Done: upload emails into newsletter list

**Comment by Wabri** [comment]
Duplicate on https://github.com/Schrodinger-Hat/schrodinger-hat/issues/131
