### ISSUE TITLE
Form signup - waiting list ecommerce

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#521]
create one

**Comment by TheJoin95** [comment]
Can I assign this to you @davideimola ?

**Comment by davideimola** [comment]
@TheJoin95 what's the desiderata? What do we need?

**Comment by TheJoin95** [comment]
We need a way to get the email for those who want to be informed about the new store

**Comment by TheJoin95** [comment]
Given the situation and the development speed, we can avoid this issue as we're going to share the link into the newsletter and social post. Closing this
