### ISSUE TITLE
Create a 3d representation with treejs

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#527]
3d model: https://github.com/Schrodinger-Hat/resources/blob/main/3Dprinter/trophy.stl

**Comment by TheJoin95** [comment]
@DanerSound I Need you on this. Can you update the trophy.stl?

**Comment by DanerSound** [comment]
![image](https://github.com/Schrodinger-Hat/osday/assets/11822185/b80a9488-071c-415b-bd2e-ae49ad25f730)

**Comment by Wabri** [comment]
Update no screenshot

**Comment by DanerSound** [comment]
that screenshot is from cura , i just update the file, but i know know why is all black

**Comment by TheJoin95** [comment]
@DanerSound why it's 14MB now?

**Comment by DanerSound** [comment]
@TheJoin95 , i dont know... is a problem ?

**Comment by TheJoin95** [comment]
@DanerSound could you try to make it lighter?

**Comment by DanerSound** [comment]
done

**Comment by TheJoin95** [comment]
@DanerSound nope, non mi funge. Mi funziona solo la versione 2023. Riesci a riprender quello e a rimuovere l'anno dal testo? Mantenendo inalterate tutte le altre impostazioni?

**Comment by DanerSound** [comment]
No no non posso editare quel file... non capisco perché fa così dopo riguardo

**Comment by LobeTia** [comment]
Gli ho dato due martellate per sistemarlo, c'erano alcuni buchi nella mesh e le normali erano invertite.

[trophy2024_normals_and_holes__repaired.stl.zip](https://github.com/Schrodinger-Hat/osday/files/15010568/trophy2024_normals_and_holes__repaired.stl.zip)

**Comment by Wabri** [comment]
@TheJoin95 riesci anche a fare il post gia' che ci sei?

**Comment by TheJoin95** [comment]
Today we're introducing Schroddy, our 3D trophy made by Andre, proudly celebrating Open Source Day 2024!
Join us as we honor the brilliance, innovation, and community spirit driving the open-source ecosystem forward.

Schroddy is our award for celebrating the phenomenal speakers, the expertise and the incredible achievements fueling the open-source ecosystem!

Do you want him? Well, try to submit a session for the next Open Source Day! We're not selling him!

Well, as you may know now, everything that we made or do is fully transparents and open sourced so if you're going to have a look at our website repository you could, of course, print Schroddy at home (if you have a 3D printer).

https://osday.dev/schroddy

⁠osday24 #Schroddy


Dovremmo mettere come immagine una foto di uno speaker che alza il trofeo

**Comment by Wabri** [comment]
Fatto
