### ISSUE TITLE
Update to node v20

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#531]
We should move to node20, it's unacceptable to still be at v16

Deploy: we should check whenever netlify it's automatically build with the correct node version

**Comment by TheJoin95** [comment]
@Readpato would you like to try it out?

I did once for another SH project, if you like I let you enjoy the process

**Comment by Readpato** [comment]
Yeah sure, I have already done it for the website so it should be straightforward

**Comment by TheJoin95** [comment]
Top, thanks

**Comment by TheJoin95** [comment]
Can we close this @Readpato or is not yet done?

**Comment by Readpato** [comment]
Can be closed 👍
