### ISSUE TITLE
Update terminal.osday.dev with the latest infos for 2025 edition

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#533]
As per title.

Bonus: we should decide whether we maintain this joke website or not cc @Wabri

**Comment by TheJoin95** [comment]
@Readpato would you like to take this?

**Comment by Readpato** [comment]
Yes, ma mi dai un po' più di contesto? E tutto dentro del repo di osday?

**Comment by TheJoin95** [comment]
@404answernotfound I need your choice on whenever maintain or drop the terminal.osday.dev easter egg website

**Comment by TheJoin95** [comment]
Done, updated.

**Comment by TheJoin95** [comment]
@404answernotfound we should create a social post to announce that we have a terminal.osday.dev
