### ISSUE TITLE
[11/12/2024]: Countdown to event

### ISSUE THREAD

**Issue by Readpato** [Schrodinger-Hat/osday-2023#545]
This are just proposals, the actual dates will need to be edited once we know when we want to publish it, still missing an image, maybe something with shroddy and the actual countdown?

Proposal 1:

⏰ 120 Days to Go! #OSDayFI 

The countdown to Open Source Day 2025 has begun! In just 120 days, Florence will welcome open source enthusiasts from around the globe.

🎯 Tech talks
🤝 Networking
🎁 Giveaways
💻 Hybrid format

🎟️ FREE tickets: osday.dev
🤝 Sponsor the event: osday.dev/osday2025-sponsorship-proposal.pdf
✉️ Contact: events@schroedinger-hat.org

See you on March 21st at Nana Bianca! 

#OSDay25 #OpenSource #TechConference

<hr>

Proposal 2:

⏰ 120 Days Until OSDay 2025! 

The excitement is building! In just 120 days, Florence will become the heart of open source innovation and community collaboration.

What to Look Forward To:
🎯 Expert-led tech talks
🤝 Connect with OS maintainers
🎁 Tech giveaways from sponsors
💻 Join in-person or online
☕️ Networking breaks

Want to be part of making this happen?
📢 Sponsorship opportunities available!
→ osday.dev/osday2025-sponsorship-proposal.pdf
→ events@schroedinger-hat.org

🎟️ Grab your FREE ticket now at osday.dev
📍 March 21st, 2025 | Nana Bianca, Florence

Together, let's make #OSDay25 unforgettable!

#OSDayFI #OpenSource #TechCommunity #Florence

<hr>

Proposal 3
⏰ The Final Countdown: 120 Days to OSDay 2025! 

The anticipation is building as we approach the 4th edition of Open Source Day in Florence! In just 120 days, we'll bring together the brightest minds in open source for an unforgettable day of learning, sharing, and collaboration.

What Makes OSDay 2025 Special:
🎯 Curated talks from passionate OS contributors
🤝 Face-to-face networking with maintainers
💡 Knowledge sharing across all experience levels
🎁 Tech giveaways from our sponsors
💻 Hybrid format: Join in Florence or tune in online
🌟 100% FREE for all attendees

Schedule Snapshot:
🕒 8:30 AM - Doors Open
🕙 10:00 AM - Talks Begin
📍 Location: Nana Bianca, Florence

🤝 Support the Open Source Community:
Want to help keep OSDay free and amazing? We're looking for sponsors who share our passion for open source innovation!
→ Review sponsorship opportunities: osday.dev/osday2025-sponsorship-proposal.pdf
→ Contact us: events@schroedinger-hat.org

Don't Miss Out:
🎟️ Reserve your FREE spot now at osday.dev
📅 Add March 21st, 2025 to your calendar

Join us in making #OSDay25 the most impactful edition yet!

#OSDayFI #OpenSource #TechConference #DevCommunity #Florence #Innovation #Technology

**Comment by TheJoin95** [comment]
The second one is looking good.

I let you choose the date of publish and the image of the post
Tag all of us + nana bianca

**Comment by Readpato** [comment]
Updated:

⏰ 102 Days Until OSDay 2025!

The excitement is building! In just 102 days, Florence will become the heart of open source innovation and community collaboration.

What to Look Forward To:
🎯 Expert-led tech talks
🤝 Connect with OS maintainers 
🎁 Tech giveaways from sponsors
💻 Join in-person or online
☕️ Networking breaks

Want to be part of making this happen? 
📢 Sponsorship opportunities available!
→ osday.dev/osday2025-sponsorship-proposal.pdf
→ events@schroedinger-hat.org

🎟️ Grab your FREE ticket now at osday.dev
📍 March 21st, 2025 | Nana Bianca, Florence

Together, let's make #OSDay25 unforgettable!

#OSDayFI #OpenSource #TechCommunity #Florence

**Comment by Readpato** [comment]
Image proposal (Design is my passion):
![Facebook post - 1 (1)](https://github.com/user-attachments/assets/f7d74700-01b5-475e-8c3c-1091bb9962c5)

**Comment by TheJoin95** [comment]
Noice! All good

**Comment by Readpato** [comment]
Scheduled

**Comment by Readpato** [comment]
Updated given changing of posts:

⏰ 100 Days Until OSDay 2025!

The excitement is building! In just 100 days, Florence will become the heart of open source innovation and community collaboration.

What to Look Forward To:
🎯 Expert-led tech talks
🤝 Connect with OS maintainers
🎁 Tech giveaways from sponsors
💻 Join in-person or online
☕️ Networking breaks

Want to be part of making this happen?
📢 Sponsorship opportunities available!
→ osday.dev/osday2025-sponsorship-proposal.pdf
→ events@schroedinger-hat.org

🎟️ Grab your FREE ticket now at osday.dev
📍 March 21st, 2025 | Nana Bianca, Florence

Together, let's make #OSDay25 unforgettable!

#OSDayFI #OpenSource #TechCommunity #Florence

**Comment by Readpato** [comment]
Reopened because it moves to the 11 instead of the 9/12

**Comment by Readpato** [comment]
Chuding as done
