### ISSUE TITLE
Background image not fixed

### ISSUE THREAD

**Issue by nicpuppa** [Schrodinger-Hat/osday-2023#60]
There is a problem with the background image, is not fixed but change his position in every page.
![38FBEDB9-A1FB-4EA8-B249-1C61517A1CCD](https://user-images.githubusercontent.com/72783243/202846441-f2715bb5-992f-4d89-a208-c60ba00b2ef7.png)
![867131CF-9380-4176-AAB7-F70C727DB155](https://user-images.githubusercontent.com/72783243/202846443-d36c1cb7-1269-425c-b12c-38ab015cd7be.png)

**Comment by gogoiakash2311** [comment]
Can you assign this to me

**Comment by 404answernotfound** [comment]
> Can you assign this to me

still interested? :) @gogoiakash2311

**Comment by gogoiakash2311** [comment]
Yes! I'll be happy to help 😊

**Comment by gogoiakash2311** [comment]
@404answernotfound The cards on the sponsor page are oversized and because of that the background image is getting zoomed in. So to resolve the issue i have to resize the cards. Do you want me to do that??

**Comment by TheJoin95** [comment]
Go ahead

**Comment by TheJoin95** [comment]
We might need to do a restyling on the sponsor page

**Comment by gogoiakash2311** [comment]
Okay..i tried everything. And i think it'll be resolved by resizing the cards only

**Comment by TheJoin95** [comment]
@gogoiakash2311 I'm going to take this since no PR came in

**Comment by gogoiakash2311** [comment]
Sorry. since my exams are going on. I'm unable to work on this issue.

**Comment by nicpuppa** [comment]
The mobile version is still broken

**Comment by TheJoin95** [comment]
Estoy loco
