### ISSUE TITLE
Add send email button in sponsor page

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday-2023#65]
We need a CTA

**Comment by nicpuppa** [comment]
@TheJoin95 where would you insert the button ? In each card ?

**Comment by TheJoin95** [comment]
We could insert the button in each card, by adding a mailto link with the subject parameter relative to the tier (e.g. mailto:osday@schrodinger-hat.it?subject=Gold tier), or just a generic button in a new line under the sponsor page description and before the cards.

Let's see which one fits better

**Comment by TheJoin95** [comment]
It should be above the fold of the page, not in the footer. Could you please make this change? We should have just on description div
