### ISSUE TITLE
scroll event on dei page is broken

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday-2023#86]
https://user-images.githubusercontent.com/12409541/204595184-62177851-0003-4d60-ba51-3df1970a7809.mov

**Comment by Wabri** [comment]
Still here

https://user-images.githubusercontent.com/12409541/205327535-8c838b00-32bb-44e8-b1ff-795566c0b66b.mov

**Comment by TheJoin95** [comment]
Which resolution do you have, son?
